/*package drools;

import com.cts.training.day3.Product;
import com.cts.training.day3.Person;
import com.cts.training.day3.Address;
import java.util.ArrayList;

rule "accumulate-example"

when

   accumulate( $person:Person($age:age>40));
   
                $min:min($age),
                $max:max($age),
                $avg:average($age),
                $count:count($age),
                //$avg>25
                )
                
 then
 
    //System.out.println("no of persons with age greater than 40"+$size);
    System.out.println("min "+$min);   
    System.out.println("max "+$max); 
    System.out.println("avg "+$average); 
    System.out.println("count "+$count);     
    
 end  */        